# Generated by Django 5.1.1 on 2025-05-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0005_alter_student_class_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_year',
            field=models.CharField(max_length=20),
        ),
    ]
