# Generated by Django 5.1.1 on 2025-04-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0004_instructor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_year',
            field=models.CharField(choices=[('F', 'Freshman'), ('S', 'Sophomore'), ('J', 'Junior Year'), ('A', 'Advanced Year')], max_length=1),
        ),
    ]
