# Generated by Django 5.1.1 on 2025-05-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0006_alter_student_class_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('N', 'Not Active')], default='N', max_length=1),
        ),
    ]
