# Generated by Django 5.1.1 on 2025-05-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0007_alter_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('A', 'ACTIVE'), ('P', 'PENDING')], default='N', max_length=1),
        ),
    ]
